export const CREATE_AUTHOR = 'CREATE_AUTHOR';
export const SET_AUTHORS = 'SET_AUTHORS';
export const ADD_COURSES_AUTHOR = 'ADD_COURSES_AUTHOR';
export const DELETE_COURSES_AUTHOR = 'DELETE_COURSES_AUTHOR';
export const SET_COURSES_AUTHORS = 'SET_COURSES_AUTHORS';
