export const SET_COURSES = 'SET_COURSES';
export const SEARCH_COURSES = 'SEARCH_COURSES';
export const ADD_NEW_COURSE = 'ADD_NEW_COURSE';
export const DELETE_COURSE = 'DELETE_COURSE';
export const UPDATE_COURSE = 'UPDATE_COURSE';
